pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: "This PR has conflicts. @{{author}}, is it possible for you to fix them? We can sync to discuss the problem should there be one"
  - name: Hotfix merge
    conditions:
      - "#approved-reviews-by>=2"
      - "head~=^hotfix"
      - "base=stable"
    actions:
      backport:
        branches:
          - dev