targets:
  $default:
    builders:
      parabeac_core|json_serializable:
        generate_for:
          include:
            - lib/**
          exclude:
            - test/lib/**
        options:
          any_map: false
          checked: false
          create_factory: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          ignore_unannotated: true
          include_if_null: true
          nullable: true