targets:
  parabeac_core:
    builders:
      parabeac_core|json_serializable:
        generate_for:
          - lib/**
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          ignore_unannotated: false
          include_if_null: true
          nullable: true