name: parabeac_core
description: A starting point for Dart libraries or applications.
version: 1.4.6
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  archive: ^2.0.11
  json_serializable: ^3.5.0
  build_runner: ^1.10.0
  mockito: ^4.1.1
  hex: ^0.1.2
  build: ^1.3.0
  logger: ^0.8.3
  uuid: ^2.1.0
  quick_log: ^1.1.3
  sentry: ^5.1.0
  http2: ^1.0.1
  recase: "^3.0.0"
  tuple: ^1.0.3
  azblob: ^1.0.3
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_config: ^0.4.2
# dependency_overrides:
#   analyzer: '0.39.14'
