name: Dart CI

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Flutter action
      uses: subosito/flutter-action@v1.4.0    
    
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
      env:
        FIG_API_KEY: ${{ secrets.FIG_API_KEY }}
