name: Dart CI

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
      env:
        FIG_API_KEY: ${{ secrets.FIG_API_KEY }}
